### ISSUE TITLE
esbuild postinstall script fails

### ISSUE THREAD

**Issue by intrnl** [orogene/orogene#250]
orogene version: 0.3.22

esbuild's postinstall involves replacing the `bin/esbuild` file with native binaries from `@esbuild/<platform>/bin/esbuild`[^1] and then checks that the esbuild version matches as a just in case thing[^2].

[^1]: https://github.com/evanw/esbuild/blob/0776a4be2bb80980482b123a9a05dbf55cc35683/lib/npm/node-install.ts#L171
[^2]: https://github.com/evanw/esbuild/blob/0776a4be2bb80980482b123a9a05dbf55cc35683/lib/npm/node-install.ts#L14

it seems that it's failing to do that version check because the binaries weren't marked as executable prior to the postinstall step, as indicated in the log below with the `EACCES` error code.

<details>
<summary>Relevant log</summary>

```
[2m   0.000036248s[0m [34mDEBUG[0m Running command: /home/intrnl/.local/share/fnm/node-versions/v19.8.1/installation/lib/node_modules/oro/node_modules/binary-install/node_modules/.bin/oro add -D esbuild
[2m   0.382159048s[0m [32m INFO[0m 🔍 Resolved esbuild to esbuild@^0.17.17.
[2m   0.382167708s[0m [34mDEBUG[0m Adding esbuild@^0.17.17 to devDependencies.
[2m   0.382477249s[0m [32m INFO[0m 📝 Updated package.json with 1 new devDependency.
[2m   1.761642358s[0m [34mDEBUG[0m [1mresolving[0m[2m:[0m Resolved graph of 24 nodes in 1374ms
[2m   1.761753407s[0m [32m INFO[0m 🔍 Resolved 24 packages in 1.379s.
[2m   1.762174905s[0m [34mDEBUG[0m [1mprune[0m[2m:[0m No metadata file found in node_modules/. Pruned entire node_modules/ directory in 0ms.
[2m   1.762280437s[0m [32m INFO[0m 🧹 Pruned 0 packages in 0s.
[2m   1.762367181s[0m [34mDEBUG[0m [1mextract[0m[2m:[0m Applying node_modules/...
[2m   1.762615330s[0m [34mDEBUG[0m [1mextract[0m[2m:[0m reflink support check failed. Files will be hard linked or copied. (Operation not supported (os error 95))
[2m   1.835934659s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted esbuild to %ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild in 64ms. 1/24 done. [3min_flight[0m[2m=[0m22
[2m   6.572918973s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-mips64el to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-mips64el@9a79efba/node_modules/@esbuild/linux-mips64el in 4801ms. 2/24 done. [3min_flight[0m[2m=[0m21
[2m   7.482372356s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/freebsd-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/freebsd-x64@4d05b87a/node_modules/@esbuild/freebsd-x64 in 5710ms. 3/24 done. [3min_flight[0m[2m=[0m20
[2m   8.226554583s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-s390x to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-s390x@6505495d/node_modules/@esbuild/linux-s390x in 6454ms. 4/24 done. [3min_flight[0m[2m=[0m19
[2m  10.553095542s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-x64@bc30f4e1/node_modules/@esbuild/linux-x64 in 8781ms. 5/24 done. [3min_flight[0m[2m=[0m18
[2m  11.068127567s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-arm64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-arm64@8d34583f/node_modules/@esbuild/linux-arm64 in 9296ms. 6/24 done. [3min_flight[0m[2m=[0m17
[2m  11.704024584s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-arm to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-arm@e47d5ceb/node_modules/@esbuild/linux-arm in 9931ms. 7/24 done. [3min_flight[0m[2m=[0m16
[2m  11.879222432s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/android-arm64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/android-arm64@0bc52f3d/node_modules/@esbuild/android-arm64 in 10108ms. 8/24 done. [3min_flight[0m[2m=[0m15
[2m  11.923084036s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/darwin-arm64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/darwin-arm64@f3a1a24e/node_modules/@esbuild/darwin-arm64 in 10151ms. 9/24 done. [3min_flight[0m[2m=[0m14
[2m  12.138101367s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/sunos-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/sunos-x64@825bc202/node_modules/@esbuild/sunos-x64 in 10367ms. 10/24 done. [3min_flight[0m[2m=[0m13
[2m  12.965170511s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/openbsd-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/openbsd-x64@1999f06f/node_modules/@esbuild/openbsd-x64 in 11193ms. 11/24 done. [3min_flight[0m[2m=[0m12
[2m  13.312805321s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/freebsd-arm64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/freebsd-arm64@2fba95f2/node_modules/@esbuild/freebsd-arm64 in 11540ms. 12/24 done. [3min_flight[0m[2m=[0m11
[2m  13.340690867s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-loong64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-loong64@3cf8fd5c/node_modules/@esbuild/linux-loong64 in 11569ms. 13/24 done. [3min_flight[0m[2m=[0m10
[2m  13.801892446s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/android-arm to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/android-arm@2d4e505e/node_modules/@esbuild/android-arm in 12030ms. 14/24 done. [3min_flight[0m[2m=[0m9
[2m  15.193785308s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/darwin-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/darwin-x64@6e44a14a/node_modules/@esbuild/darwin-x64 in 13422ms. 15/24 done. [3min_flight[0m[2m=[0m8
[2m  15.211396856s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/win32-ia32 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/win32-ia32@1dad443f/node_modules/@esbuild/win32-ia32 in 13439ms. 16/24 done. [3min_flight[0m[2m=[0m7
[2m  15.237928998s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-ia32 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-ia32@3ac71882/node_modules/@esbuild/linux-ia32 in 13466ms. 17/24 done. [3min_flight[0m[2m=[0m6
[2m  15.390753780s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-riscv64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-riscv64@fd5a50ba/node_modules/@esbuild/linux-riscv64 in 13619ms. 18/24 done. [3min_flight[0m[2m=[0m5
[2m  15.742941155s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/netbsd-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/netbsd-x64@a54fc4c9/node_modules/@esbuild/netbsd-x64 in 13971ms. 19/24 done. [3min_flight[0m[2m=[0m4
[2m  15.995632944s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/win32-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/win32-x64@79cc3bf9/node_modules/@esbuild/win32-x64 in 14223ms. 20/24 done. [3min_flight[0m[2m=[0m3
[2m  16.670363429s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/linux-ppc64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/linux-ppc64@03d54960/node_modules/@esbuild/linux-ppc64 in 14898ms. 21/24 done. [3min_flight[0m[2m=[0m2
[2m  16.814059970s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/android-x64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/android-x64@98b4021b/node_modules/@esbuild/android-x64 in 15042ms. 22/24 done. [3min_flight[0m[2m=[0m1
[2m  18.539618629s[0m [35mTRACE[0m [1mextract[0m[2m:[0m Extracted @esbuild/win32-arm64 to %ROOT_FOLDER%/node_modules/.oro-store/@esbuild/win32-arm64@1b43e93d/node_modules/@esbuild/win32-arm64 in 16767ms. 23/24 done. [3min_flight[0m[2m=[0m0
[2m  18.539904633s[0m [34mDEBUG[0m [1mextract[0m[2m:[0m Extracted 23 packages in 16777ms.
[2m  18.540004647s[0m [32m INFO[0m 📦 Extracted 23 packages in 16.777s.
[2m  18.540067854s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Running lifecycle scripts...
[2m  18.540071695s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Running preinstall lifecycle scripts
[2m  18.540322079s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Ran lifecycle scripts for preinstall in 0ms.
[2m  18.540325991s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Linking bins...
[2m  18.540452405s[0m [35mTRACE[0m Linked bin for esbuild from %ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild/bin/esbuild to %ROOT_FOLDER%/node_modules/.bin/esbuild
[2m  18.540505136s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Linked 1 package bins in 0ms.
[2m  18.540508418s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Running install lifecycle scripts
[2m  18.540636928s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Ran lifecycle scripts for install in 0ms.
[2m  18.540641747s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m Running postinstall lifecycle scripts
[2m  18.540956805s[0m [35mTRACE[0m Executing script for event 'postinstall' for package at %ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild: node install.js
[2m  18.584548248s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild: node:internal/errors:490
[2m  18.584628986s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     ErrorCaptureStackTrace(err);
[2m  18.584654269s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     ^
[2m  18.584678085s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild: 
[2m  18.584702320s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild: <ref *1> Error: spawnSync %ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild/bin/esbuild EACCES
[2m  18.584744924s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     at Object.spawnSync (node:internal/child_process:1117:20)
[2m  18.584770067s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     at spawnSync (node:child_process:871:24)
[2m  18.584787667s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     at Object.execFileSync (node:child_process:914:15)
[2m  18.584806874s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     at validateBinaryVersion (%ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild/install.js:98:28)
[2m  18.584831598s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:     at %ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild/install.js:285:5 {
[2m  18.584852481s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   errno: -13,
[2m  18.584870570s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   code: 'EACCES',
[2m  18.584889427s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   syscall: 'spawnSync %ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild/bin/esbuild',
[2m  18.584913313s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   path: '%ROOT_FOLDER%/node_modules/.oro-store/esbuild@58515e96/node_modules/esbuild/bin/esbuild',
[2m  18.584930913s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   spawnargs: [ '--version' ],
[2m  18.584949980s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   error: [Circular *1],
[2m  18.584969117s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   status: null,
[2m  18.584990000s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   signal: null,
[2m  18.585008159s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   output: null,
[2m  18.585029181s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   pid: 0,
[2m  18.585043918s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   stdout: null,
[2m  18.585059214s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild:   stderr: null
[2m  18.585073950s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild: }
[2m  18.585088757s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild: 
[2m  18.585103144s[0m [34mDEBUG[0m [1mBuilding[0m[2m:[0m[1mscript::{name}::{event}[0m[2m:[0m stderr::esbuild: Node.js v19.8.1
[2m  18.587744855s[0m [34mDEBUG[0m [31moro_script::script_error[0m ([36;1;4mhttps://docs.rs/oro-script/0.3.22/oro_script/enum.OroScriptError.html#variant.ScriptError[0m)

  [31m×[0m Script exited with code 1

[2m  18.587895225s[0m [33m WARN[0m A debug log was written to /home/intrnl/.cache/orogene/_logs/oro-debug-2023-04-18-21-44-49.953-0.log
```

</details>

**Comment by zkat** [comment]
Oho. Looks like [NPM sets the executable flag on all extracted files if they're registered as bins in a package](https://github.com/npm/pacote/blob/main/lib/fetcher.js#L423), which results in this replacement already being executable when it gets moved in (it defaults to `-rw----`).

Thanks for the report, and good catch!

**Comment by zkat** [comment]
I think the fix for this is tied to some of the planned changes in #220. Namely, having the tarball extraction process be aware of what packages have bins and scripts in them, and record this in an optimized way. Once we have this, we can either make sure to `prefer_copy` on extraction when the target file is a package's bin, or just go ahead and chmod it directly in the cache, so anything hard linked sees the new perms.

My preference right now is for the first alternative, because I feel like messing around with perms on hard-link-shared files is a bit iffy, especially in a content-addressable cache.
